 @isTest
 public class AccountTriggerHandlerTest {
//     @isTest
//     static void test1_Insert_CPF_Valido() {
//         Test.startTest();
//         Account acc1 = new Account(Name='Test1', CPF__c= '123.123.123-12');
//         insert acc1;
//         Test.stopTest();
//     }

//     @isTest
//     static void teste2_Update_CPF_Valido() {                                     //metodo
//         Test.startTest();                                                        //inicia teste
//         Account acc1 = new Account(Name='Test2', CPF__c= '123.123.123-12');      //estancia e declara nova conta
//         insert acc1;                                                             //insere a conta declarada
//         acc1.CPF__c = '121.121.121-12';                                          //altera conta declarada
//         update acc1;                                                             //update
//         Test.stopTest();                                                         //fim teste
//     }
//     @isTest
//     static void test3_CPF_Invalido() {
//         Test.startTest();
//         Account acc1 = new Account(Name= 'Test3', CPF__c = '123.123.123');
//         try {
//             insert acc1;
//         } catch (DmlException e) {
//             System.assert(e.getMessage().contains(Label.ACCOUNT_CPF_ERROR_MESSAGE));
//         }
//         Test.stopTest();
//     }
 }